version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
      labels:
          - "dependencies"
      assignees:
          - "6jt8"
      open-pull-requests-limit: 10
